### ISSUE TITLE
Configuration API Rate Limits

### ISSUE THREAD

**Issue by vitrecca** [opsgenie/opsgenie-configuration-backup#21]
It would be grate if we can set max speed in API calls (max concurrent threads in the pool and wait time after each api call or file write). In my case OpsGenie keeps cancelling my exports because max config api rate is reached.
Thanks

**Comment by mbaris** [comment]
We are aware of this problem and created an internal issue. Thanks for reporting it on both intercom and here.

**Comment by bneqld** [comment]
Is there any kind of a timeline for this to get solved?

**Comment by mbaris** [comment]
Sorry for any inconvenience. v0.19.0 should fix your problem. We have introduced a retry policy with an exponential backoff with this version.
