### ISSUE TITLE
User notification policies have unstable list order

### ISSUE THREAD

**Issue by iainelder** [opsgenie/opsgenie-configuration-backup#41]
This was originally discussed as part of a larget ordering issue in #33.

The list of steps in the user notification policies still appears to be changing the order of its elements when in reality nothing in the cofiguration has changed.

In this example, the email address and the mobile application swap places even though nothing in the configuration actually changed :

![user-notification-policy-step-list-order](https://user-images.githubusercontent.com/5024311/75702999-e4c2db00-5cb6-11ea-9a37-d07c4b0d669e.png)

This makes the git diffs less useful for real changes because each run of the backup tool generates this noise even when there are no changes.

**Comment by iainelder** [comment]
Opsgenie support has opened a ticket with the development team about this.

The internal reference number is OGS-564.

**Comment by alpgurtan** [comment]
Hi 👋 , 
Sorry for letting you wait but we updated our [REST API](https://docs.opsgenie.com/docs/notification-rule-step-api) for preserving the order of it... It should be fixed right now. I'm closing this issue but feel free to open it if there is a problem

**Comment by iainelder** [comment]
Great, thanks! I'll check the output of the next backups and let you know if I have any more questions.
