### ISSUE TITLE
Schedule time restrictions have unstable list order

### ISSUE THREAD

**Issue by iainelder** [opsgenie/opsgenie-configuration-backup#43]
This appears related to another ordering bug that was discussed in #41.

The list of time restrictions in the user notification policies still appears to be changing the order of its elements when in reality nothing in the configuration has changed.

This makes the git diffs less useful for real changes because each run of the backup tool generates this noise even when there are no changes.

In this example, the days of the week of the two rotations appear to change order even though nothing in the configuration actually changed:

![fake-diff](https://user-images.githubusercontent.com/5024311/84773957-709a1200-afdd-11ea-9fe8-aadd33db7995.png)

**Comment by iainelder** [comment]
Discussed with Opsgenie support. It has been raised with the development team.

The internal reference number is OGS-1509.

**Comment by abhisgup-atl** [comment]
Hi,

We have updated our backup tool to make the restrictions order stable across runs. It should be fixed right now. I'm closing this issue but feel free to open it if there is a problem.

https://github.com/opsgenie/opsgenie-configuration-backup/releases/tag/backup-v0.23.4 has the fix.
